[package]
name = "init-shim-rs"
version = "1.0.0"
authors = ["Stefan Reiter <s.reiter@proxmox.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0"
nix = { version = "0.29", features = ["fs", "mount", "process", "reboot"] }
